# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.items.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', gallery.items.fields.ThumbnailImageField(upload_to='photo')),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
